"""
smiles2xyz.py

Command-line tool to convert SMILES strings into 3D XYZ files using RDKit.

Examples
--------
Single SMILES:

    python smiles2xyz.py --smiles "CCO" --output ethanol.xyz

Batch from file (one SMILES per line):

    python smiles2xyz.py --smiles-file input_smiles.txt --output-prefix mol_

"""

import argparse
from typing import Optional, List

from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem.rdchem import Mol


def smiles_to_xyz(smiles: str, output_file: str) -> None:
    """
    Convert a SMILES string into a 3D XYZ coordinate file using RDKit.

    Steps:
        1. Parse SMILES into an RDKit Mol object
        2. Add hydrogens
        3. Generate 3D coordinates using ETKDG
        4. Optimize geometry using UFF
        5. Write positions to an XYZ file

    Args:
        smiles (str): Input SMILES string.
        output_file (str): Path to save the resulting XYZ file.

    Raises:
        ValueError: If SMILES cannot be parsed.
        RuntimeError: If 3D embedding (ETKDG) fails.
    """
    # Parse SMILES
    mol: Optional[Mol] = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"Invalid SMILES string: {smiles}")

    # Add hydrogens
    mol = Chem.AddHs(mol)

    # Embed 3D coordinates
    success = AllChem.EmbedMolecule(mol, AllChem.ETKDG())
    if success != 0:
        raise RuntimeError(f"3D embedding failed for SMILES: {smiles}")

    # Optimize geometry (UFF)
    success = AllChem.UFFOptimizeMolecule(mol)
    if success != 0:
        print(f"Warning: Geometry optimization did not fully converge for {smiles}.")

    # Write XYZ file
    conf = mol.GetConformer()
    with open(output_file, "w") as f:
        f.write(f"{mol.GetNumAtoms()}\n")
        f.write(f"Generated by RDKit from SMILES: {smiles}\n")

        for atom in mol.GetAtoms():
            pos = conf.GetAtomPosition(atom.GetIdx())
            symbol = atom.GetSymbol()
            f.write(f"{symbol} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}\n")

    print(f"XYZ written to: {output_file}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert SMILES to 3D XYZ coordinates using RDKit."
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--smiles",
        type=str,
        help="Single SMILES string to convert."
    )
    group.add_argument(
        "--smiles-file",
        type=str,
        help="Path to a text file containing one SMILES per line."
    )

    parser.add_argument(
        "--output",
        type=str,
        default="molecule.xyz",
        help="Output XYZ file name for single SMILES mode. [default: molecule.xyz]"
    )
    parser.add_argument(
        "--output-prefix",
        type=str,
        default="mol_",
        help="Prefix for XYZ file names in batch mode (used with --smiles-file). "
             "Each molecule will be saved as <prefix><index>.xyz. [default: mol_]"
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if args.smiles:
        # Single SMILES mode
        smiles = args.smiles.strip()
        smiles_to_xyz(smiles, args.output)

    elif args.smiles_file:
        # Batch mode: read SMILES from file
        with open(args.smiles_file, "r") as f:
            smiles_list: List[str] = [
                line.strip() for line in f
                if line.strip() and not line.strip().startswith("#")
            ]

        if not smiles_list:
            raise ValueError(f"No valid SMILES found in file: {args.smiles_file}")

        for idx, smi in enumerate(smiles_list, start=1):
            output_file = f"{args.output_prefix}{idx}.xyz"
            try:
                smiles_to_xyz(smi, output_file)
            except Exception as e:
                print(f"Failed for line {idx} ('{smi}'): {e}")


if __name__ == "__main__":
    main()
